version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-flask-app

permissions:
  - object: /home/ubuntu/my-flask-app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
